### ISSUE TITLE
SSLError - Issue with certificate

### ISSUE THREAD

**Issue by belisards** [fragilefamilieschallenge/ffmetadata-py#4]
Hi,

Is this project still active? I am getting the following error when I try to use the package:

```
ff.select('ce3datey')

SSLError: HTTPSConnectionPool(host='api.metadata.fragilefamilies.princeton.edu', port=443): Max retries exceeded with url: [/variable/ce3datey](https://file+.vscode-resource.vscode-cdn.net/variable/ce3datey) (Caused by SSLError(CertificateError("hostname 'api.metadata.fragilefamilies.princeton.edu' doesn't match 'ffs-api.princeton.edu'")))
```

(Python 3.10.6)

**Comment by vineetbansal** [comment]
Hello @belisards - thanks for pointing out the issue. The API endpoint for the project recently underwent a change. It's no longer `http://api.metadata.fragilefamilies.princeton.edu`, but `https://api.metadata.ffcws.princeton.edu`. I've made the change in the code accordingly and bumped up the version to `2.0.0.`. Let us know if you're still encountering a problem.

**Comment by belisards** [comment]
Hi @vineetbansal, thank you! I removed my previous version and re-installed it using this Github repo instead of PyPi, and I can confirm that it is working now.

**Comment by vineetbansal** [comment]
Great to hear @belisards - we've updated the package version on PyPI to `2.0.0` as well.
